export default function sitemap() {
  const base = "https://sealofaudit.com";
  const routes = [
    "",    "/services", "/services/cms-warning-letter-response", "/services/mrf-remediation",
    "/how-it-works", "/pricing", "/sample-report", "/insights", "/contact",
    "/blog/cms-mrf-requirements-2026", "/blog/cms-fines-hospital-price-transparency",
    "/blog/find-hospital-mrf-file", "/blog/payer-specific-negotiated-rates-guide",
    "/blog/hospital-price-transparency-requirements", "/blog/cms-shoppable-services-list",
    "/blog/standard-charges-vs-negotiated-rates", "/blog/cms-price-transparency-fines-list",
    "/blog/mrf-json-format-guide", "/blog/price-transparency-compliance-checklist",
    "/blog/cms-enforcement-actions-2026",
    "/blog/mrf-vs-price-estimator-tool",
    "/blog/hospital-price-transparency-lawsuits",
    "/blog/cms-warns-500-hospitals-2026", "/blog/cms-enforcement-tracker-2026",
    "/blog/no-more-grace-period-enforcement-2026", "/blog/from-warning-letter-to-fine-timeline",
    "/blog/pinnacle-hospital-fined-twice", "/blog/largest-cms-fine-northside",
    "/blog/real-cost-of-noncompliance", "/blog/28-hospitals-fined-what-they-got-wrong",
    "/blog/fix-it-later-most-expensive-sentence", "/blog/most-warning-letters-formatting-errors",
    "/blog/warning-letter-vs-cap-vs-fine", "/blog/escalation-rate-224-percent",
    "/blog/what-is-machine-readable-file", "/blog/allowed-amount-metrics-2026",
    "/blog/compliance-attestation-signer", "/blog/shoppable-services-101",
    "/blog/5-technical-errors-trigger-warning-letters", "/blog/diy-vs-professional-mrf-audit",
    "/blog/what-to-ask-before-hiring-mrf-auditor", "/blog/corrective-action-plan-45-days",
    "/partners",
    "/price-transparency-file-guide",
    "/compliance-department",
    "/penalty-calculator",
    "/blog",
    "/compare", "/compare/sealofaudit-vs-kpmg",
    "/compare/sealofaudit-vs-doing-it-yourself",
    "/compare/mrf-audit-vs-price-transparency-consultant",
    "/insights/state/colorado-hospital-price-transparency-requirements",
    "/insights/state/oregon-hospital-price-transparency-requirements",
    "/insights/state/texas-hospital-price-transparency-requirements",
    "/insights/state/california-hospital-price-transparency-requirements",
    "/insights/state/massachusetts-hospital-price-transparency-requirements",
    "/insights/state/maryland-hospital-price-transparency-requirements",
    "/insights/state/washington-hospital-price-transparency-requirements",
    "/insights/state/nevada-hospital-price-transparency-requirements",
  ];
  return routes.map((r) => ({
    url: `${base}${r}`,
    lastModified: new Date(),
    changeFrequency: r === "" ? "weekly" : "monthly",
    priority: r === "" ? 1 : 0.7,
  }));
}
